export const descriptionsObj: { [key: string]: string } = {
  DP1: 'Criar',
  DP2: 'Listar',
  DP3: 'Alterar',
  DP4: 'Remover',
  LP1: 'Alterar Designação Artigo',
  LP2: 'Alterar Quantidade',
  LP3: 'Alterar Preço',
  LP4: 'Alterar Imposto',
  LP5: 'Alterar Desconto',
  LP6: 'Remover Linhas',
  LP7: 'Quantidade Negativa',
  US1: 'Criar Utilizador',
  US2: 'Alterar Utilizador',
  US3: 'Listar Utilizadores',
  US4: 'Remover Utilizador',
  RP1: 'Criar Role',
  RP2: 'Alterar Role',
  RP3: 'Listar Roles',
  RP4: 'Remover Role',
  SP1: 'Tela de resumo',
  SP2: 'Extrato de cliente',
  SP3: 'Recursos humanos',
  SP4: 'estatistícas',
};
